//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceWars.Functions.Events.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpaceWarsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpaceWarsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceWars.Functions.Events.Resources.SpaceWarsResources", typeof(SpaceWarsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                   .-----.
        ///                   | |.-\ \
        ///                   | ||_|\ \
        ///                   | :   :  \
        ///                   |  :___\  \    
        ///                   | _|   :___\   
        ///                   ||_|    \   \
        ///                   ||_|    :    \
        ///                   ||_| ____\____\
        ///                   |   |    :     \
        ///                   | _ |     \     \
        ///                   || ||     :     /
        ///                   || /-`.    \   /
        ///                   &apos;-((((_|_---&apos;-&apos;
        ///                  _)____`.__` [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lamda {
            get {
                return ResourceManager.GetString("Lamda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ||                          ||
        ///||                          ||
        ///||                          ||
        ///||                          ||
        ///||                          ||
        ///||           ____           ||
        ///||         .&apos;&apos;&apos;&apos;&apos;&apos;.         ||
        ///||        /   __   \        ||
        ///||\__..-&apos;:   /\/\   :&apos;-..__/||
        ///||=__ =|=&apos;  |-()-|  &apos;=|= __=||
        ///||/  &apos;&apos;-.:   \/\/   :.-&apos;&apos;  \||
        ///||        \   &quot;&quot;   /        ||
        ///||         `.____.&apos;         ||
        ///||                          ||
        ///||                          ||
        ///||                          ||
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             //             \\
        ///            /&apos;               `\
        ///           /,&apos;     ..-..     `.\
        ///          /,&apos;   .&apos;&apos;     ``.   `.\
        ///         /,&apos;   :   .---.   :   `.\
        ///        I I   :  .&apos;\   /`.  :   I I
        ///        I b__:   . .`~&apos;. .   :__d I
        ///        I p~~:   . `._.&apos; .   :~~q I
        ///        I I   :   ./   \.   :   I I
        ///         \`.   :   `---&apos;   :   ,&apos;/
        ///          \`.   `..     ..&apos;   ,&apos;/
        ///           \`.     ``~&apos;&apos;     ,&apos;/
        ///            \`               &apos;/    
        ///             \\             //
        ///              ~       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TieAdvanced {
            get {
                return ResourceManager.GetString("TieAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   |`.                                                           ,&apos;|
        ///  |. `.                                                       ,&apos; .|
        ///  ||`. `.                                                   ,&apos; ,&apos;||
        ///  ||##`. `.                                               ,&apos; ,&apos;##||
        ///  ||####`. `.        _      _           ________        ,&apos; ,&apos;####||
        ///  ||######`. |      / |____| \         /_/__|_\_\      | ,&apos;######||
        ///  ||#######| |   ,-&apos;..::..::..`-.___,-&apos;.&apos;   :  `.`-.   | |#######||
        ///  ||#######| |   |]__[]____[] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TieBomber {
            get {
                return ResourceManager.GetString("TieBomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ||##\ \                                             / /##||
        ///  ||##| |                                             | |##||
        ///  ||###\ \                                           / /###||
        ///  ||###| |                                           | |###||
        ///  ||####\ \                                         / /####||
        ///  ||####| |                                         | |####||
        ///  ||#####\ \                                       / /#####||
        ///  ||#####| |                                       | |#####||
        ///  ||##### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TieDefender {
            get {
                return ResourceManager.GetString("TieDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ||                                                       ||
        ///  ||                                                       ||
        ///  | \                                                     / |
        ///  |. \                                                   / .|
        ///  || |                                                   | ||
        ///  ||\ \                                                 / /||
        ///  ||| |                                                 | |||
        ///  ||#\ \                                               / /#||
        ///  ||#| [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TieInterceptor {
            get {
                return ResourceManager.GetString("TieInterceptor", resourceCulture);
            }
        }
    }
}
